import {
  faBriefcase,
  faChartLine,
  faChevronLeft,
  faChevronRight,
  faClipboardCheck,
  faGraduationCap,
  faHandshake,
  faMagnifyingGlass,
  faMoon,
  faSearch,
  faShieldHalved,
  faSun,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

export const appIcons = {
  matchmaking: faHandshake,
  search: faMagnifyingGlass,
  proposals: faClipboardCheck,
  indicators: faChartLine,
  security: faShieldHalved,
  themeDark: faMoon,
  themeLight: faSun,
  previous: faChevronLeft,
  next: faChevronRight,
  education: faGraduationCap,
  experience: faBriefcase,
  close: faXmark,
  emptySearch: faSearch,
}
